import React from "react";

export default function page() {
  return (
    <div className="max-w-6xl mx-auto space-y-4 p-4">
      <h1 className="text-2xl font-medium text-[#00df9a]">Privacy Policy </h1>
      <h5 className="text-sm">by Mark Sikaundi</h5>
      <p className="text-white">
        <strong>Privacy Policy</strong> <br /> Effective date: September 01,
        2023 we are updating
      </p>
      key points
      <ul className="list-disc list-inside">
        <li>we do not collect any data</li>
        <li>we do not store any data</li>
        <li>we do not share any data</li>
        <li>we do not sell any data</li>
      </ul>
      Interpretation and Definitions
      <p className="text-white">
        Interpretation <br /> The words of which the initial letter is
        capitalized have meanings defined under the following conditions. The
        following definitions shall have the same meaning regardless of whether
        they appear in singular or in plural. Definitions <br /> For the
        purposes of this Privacy Policy: <br /> Account means a unique account
        created for You to access our Service or parts of our Service. <br />{" "}
        Company (referred to as either "the Company", "We", "Us" or "Our" in
        this Agreement) refers to Otofast. <br /> Cookies are small files that
        are placed on Your computer, mobile device or any other device by a
        website, containing the details of Your browsing history on that website
        among its many uses. <br /> Country refers to: Zambia <br /> Device
        means any device that can access the Service such as a computer, a
        cellphone or a digital tablet. <br /> Personal Data is any information
        that relates to an identified or identifiable individual. <br /> Service
        refers to the Website. <br /> Service Provider means any natural or
        legal person who processes the data on behalf of the Company. It refers
        to third-party companies or individuals employed by the Company to
        facilitate the Service, to provide the Service on behalf of the Company,
        to perform services related to the Service or to assist the Company in
        analyzing how the Service is used. <br /> Third-party Social Media
        Service refers to any website or any social network website through
        which a User can log in or create an account to use the Service. <br />{" "}
        Usage Data refers to data collected automatically, either generated by
        the use of the Service or from the Service infrastructure itself (for
        example, the duration of a page visit). <br /> Website refers to
        Otofast, accessible from https://otofastproject.com <br /> You means the
        individual accessing or using the Service, or the company, or other
        legal entity on behalf of which such individual is accessing or using
        the Service, as applicable. <br /> Collecting and Using Your Personal
        Data <br /> Types of Data Collected <br /> Personal Data <br /> While
        using Our Service, We may ask You to provide Us with certain personally
        identifiable information that can be used to contact or identify You.
        Personally identifiable information may include, but is not limited to:{" "}
        <br /> Email address <br /> Usage Data <br /> Usage Data <br /> Usage
        Data is collected automatically when using the Service. <br /> Usage
        Data may include information such as Your Device's Internet Protocol
        address (e.g. IP address), browser type, browser version, the pages of
        our Service that You visit, the time and date of Your visit, the time
        spent on those pages, unique device identifiers and other diagnostic
        data. <br /> When You access the Service by or through a mobile device,
        We may collect certain information automatically, including, but not
        limited to, the type of mobile device You use, Your mobile device unique
        ID, the IP address of Your mobile device, Your mobile operating system,
        the type of mobile Internet browser You use, unique device identifiers
        and other diagnostic data. <br /> We may also collect information that
        Your browser sends whenever You visit our Service or when You access the
        Service by or through a mobile device. <br /> Tracking Technologies and
        Cookies <br /> We use Cookies and similar tracking technologies to track
        the activity on Our Service and store certain information. Tracking
        technologies used are beacons, tags, and scripts to collect and track
        information and to improve and analyze Our Service. The technologies We
        use may include: <br /> Cookies or Browser Cookies. A cookie is a small
        file placed on Your Device. You can instruct Your browser to refuse all
        Cookies or to indicate when a Cookie is being sent. However, if You do
        not accept Cookies, You may not be able to use some parts of our
        Service. Unless you have adjusted Your browser setting so that it will
        refuse Cookies, our Service may use Cookies. <br /> Flash Cookies.
        Certain features of our Service may use local stored objects (or Flash
        Cookies) to collect and store information about Your preferences or Your
        activity on our Service. Flash Cookies are not managed by the same
        browser settings as those used for Browser Cookies. For more information
        on how You can delete Flash Cookies, please read "Where can I change the
        settings for disabling, or deleting local shared objects?" available at
        https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_{" "}
        <br /> Web Beacons. Certain sections of our Service and our emails may
        contain small electronic files known as web beacons (also referred to as
        clear gifs, pixel tags, and single-pixel gifs) that permit the Company,
        for example, to count users who have visited those pages or opened an
        email and for other related website statistics (for example, recording
        the popularity of a certain section and verifying system and server
        integrity). <br /> Cookies can be "Persistent" or "Session" Cookies.
        Persistent Cookies remain on Your personal computer or mobile device
        when You go offline, while Session Cookies are deleted as soon as You
        close Your web browser. <br /> We use both Session and Persistent
        Cookies for the purposes set out below: <br /> Necessary / Essential
        Cookies <br /> Type: Session Cookies <br /> Administered by: Us <br />{" "}
        Purpose: These Cookies are essential to provide You with services
        available through the Website and to enable You to use some of its
        features. They help to authenticate users and prevent fraudulent use of
        user accounts. Without these Cookies, the services that You have asked
        for cannot be provided, and We only use these Cookies to provide You
        with those services. <br /> Cookies Policy / Notice Acceptance Cookies{" "}
        <br /> Type: Persistent Cookies <br /> Administered by: Us <br />{" "}
        Purpose: These Cookies identify if users have accepted the use of
        cookies on the Website. <br /> Functionality Cookies <br /> Type:
        Persistent Cookies <br /> Administered by: Us <br /> Purpose: These
        Cookies allow us to remember choices You make when You use the Website,
        such as remembering your login details or language preference. The
        purpose of these Cookies is to provide You with a more personal
        experience and to avoid You having to re-enter your preferences every
        time You use the Website. <br /> For more information about the cookies
        we use and your choices regarding cookies, please visit our Cookies
        Policy or the Cookies section of our Privacy Policy. <br /> Use of Your
        Personal Data <br /> The Company may use Personal Data for the following
        purposes: <br /> To provide and maintain our Service, including to
        monitor the usage of our Service. <br /> To manage Your Account: to
        manage Your registration as a user of the Service. The Personal Data You
        provide can give You access to different functionalities of the Service
        that are available to You as a registered user. <br /> For the
        performance of a contract: the development, compliance and undertaking
        of the purchase contract for the products, items or services You have
        purchased or of any other contract with Us through the Service. <br />{" "}
        To contact You: To contact You by email, telephone calls, SMS, or other
        equivalent forms of electronic communication, such as a mobile
        application's push notifications regarding updates or informative
        communications related to the functionalities, products or contracted
        services, including the security updates, when necessary or reasonable
        for their implementation. <br /> To provide You with news, special
        offers and general information about other goods, services and events
        which we offer that are similar to those that you have already
        purchased.
      </p>
      <p className="text-white">
        To manage Your requests: To attend and manage Your requests to Us.{" "}
        <br /> To deliver targeted advertising to You: We may use Your
        information to develop and display content and advertising (and work
        with third parties who do so) tailored to Your interests and/or location
        and to measure its effectiveness. <br /> For business transfers: We may
        use Your information to evaluate or conduct a merger, divestiture,
        restructuring, reorganization, dissolution, or other sale or transfer of
        some or all of Our assets, whether as a going concern or as part of
        bankruptcy, liquidation, or similar proceeding, in which Personal Data
        held by Us about our Service users is among the assets transferred.{" "}
        <br /> For other purposes: We may use Your information for other
        purposes, such as data analysis, identifying usage trends, determining
        the effectiveness of our promotional campaigns and to evaluate and
        improve our Service, products, services, marketing and your experience.{" "}
        <br /> We may share Your personal information in the following
        situations: <br /> With Service Providers: We may share Your personal
        information with Service Providers to monitor and analyze the use of our
        Service, to contact You. <br /> For business transfers: We may share or
        transfer Your personal information in connection with, or during
        negotiations of, any merger, sale of Company assets, financing, or
        acquisition of all or a portion of Our business to another company.{" "}
        <br /> With Affiliates: We may share Your information with Our
        affiliates, in which case we will require those affiliates to honor this
        Privacy Policy. Affiliates include Our parent company and any other
        subsidiaries, joint venture partners or other companies that We control
        or that are under common control with Us. <br /> With business partners:
        We may share Your information with Our business partners to offer You
        certain products, services or promotions. <br /> With other users: when
        You share personal information or otherwise interact in the public areas
        with other users, such information may be viewed by all users and may be
        publicly distributed outside. If You interact with other users or
        register through a Third-Party Social Media Service, Your contacts on
        the Third-Party Social Media Service may see You name, profile, pictures
        and description of Your activity. Similarly, other users will be able to
        view descriptions of Your activity, communicate with You and view Your
        profile. <br /> With Your consent: We may disclose Your personal
        information for any other purpose with Your consent. <br /> Retention of
        Your Personal Data <br /> The Company will retain Your Personal Data
        only for as long as is necessary for the purposes set out in this
        Privacy Policy. We will retain and use Your Personal Data to the extent
        necessary to comply with our legal obligations (for example, if we are
        required to retain your data to comply with applicable laws), resolve
        disputes, and enforce our legal agreements and policies. <br /> The
        Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the
        functionality of Our Service, or We are legally obligated to retain this
        data for longer time periods. <br /> Transfer of Your Personal Data{" "}
        <br /> Your information, including Personal Data, is processed at the
        Company's operating offices and in any other places where the parties
        involved in the processing are located. It means that this information
        may be transferred to — and maintained on — computers located outside of
        Your state, province, country or other governmental jurisdiction where
        the data protection laws may differ than those from Your jurisdiction.{" "}
        <br /> Your consent to this Privacy Policy followed by Your submission
        of such information represents Your agreement to that transfer. <br />{" "}
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy and
        no transfer of Your Personal Data will take place to an organization or
        a country unless there are adequate controls in place including the
        security of Your data and other personal information. <br /> Disclosure
        of Your Personal Data <br /> Business Transactions <br /> If the Company
        is involved in a merger, acquisition or asset sale, Your Personal Data
        may be transferred. We will provide notice before Your Personal Data is
        transferred and becomes subject to a different Privacy Policy. <br />{" "}
        Law enforcement <br /> Under certain circumstances, the Company may be
        required to disclose Your Personal Data if required to do so by law or
        in response to valid requests by public authorities (e.g. a court or a
        government agency). <br /> Other legal requirements <br /> The Company
        may disclose Your Personal Data in the good faith belief that such
        action is necessary to: <br /> Comply with a legal obligation <br />{" "}
        Protect and defend the rights or property of the Company <br /> Prevent
        or investigate possible wrongdoing in connection with the Service <br />{" "}
        Protect the personal safety of Users of the Service or the public <br />{" "}
        Protect against legal liability <br /> Security of Your Personal Data{" "}
        <br /> The security of Your Personal Data is important to Us, but
        remember that no method of transmission over the Internet, or method of
        electronic storage is 100% secure. While We strive to use commercially
        acceptable means to protect Your Personal Data, We cannot guarantee its
        absolute security. <br /> Children's Privacy <br /> Our Service does not
        address anyone under the age of 13. We do not knowingly collect
        personally identifiable information from anyone under the age of 13. If
        You are a parent or guardian and You are aware that Your child has
        provided Us with Personal Data, please contact Us. If We become aware
        that We have collected Personal Data from anyone under the age of 13
        without verification of parental consent, We take steps to remove that
        information from Our servers. <br /> If We need to rely on consent as a
        legal basis for processing Your information and Your country requires
        consent from a parent, We may require Your parent's consent before We
        collect and use that information. <br /> Links to Other Websites <br />{" "}
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party's site. We strongly advise You to review the Privacy Policy
        of every site You visit. <br /> We have no control over and assume no
        responsibility for the content, privacy policies or practices of any
        third party sites or services. <br /> Changes to this Privacy Policy{" "}
        <br /> We may update Our Privacy Policy from time to time. We will
        notify You of any changes by posting the new Privacy Policy on this
        page. <br /> We will let You know via email and/or a prominent notice on
        Our Service, prior to the change becoming effective and update the "Last
        updated" date at the top of this Privacy Policy. <br /> You are advised
        to review this Privacy Policy periodically for any changes. Changes to
        this Privacy Policy are effective when they are posted on this page.{" "}
        <br /> Contact Us <br /> If you have any questions about this Privacy
        Policy, You can contact us: <br /> By email: support@devcircleafrica.com
        and you will be attended. <br /> By visiting this page on our website:
        {" forum.devcircleafrica.com"} <br /> By phone number: +234 810 000 0000{" "}
        <br />{" "}
      </p>
      <p className="text-white">
        <h1 className="text-2xl font-medium text-[#00df9a]">Terms of Use</h1>
        <p className="text-white">
          These Terms of Use ("Terms", "Terms of Use") govern your relationship
          with the DevCircle Africa website (the "Service") operated by
          DevCircle Africa ("us", "we", or "our"). Please read these Terms of
          Use carefully before using the Service. <br /> Your access to and use
          of the Service is conditioned on your acceptance of and compliance
          with these Terms. These Terms apply to all visitors, users and others
          who access or use the Service. <br /> By accessing or using the
          Service you agree to be bound by these Terms. If you disagree with any
          part of the terms then you may not access the Service. <br /> Accounts{" "}
          <br /> When you create an account with us, you must provide us
          information that is accurate, complete, and current at all times.
          Failure to do so constitutes a breach of the Terms, which may result
          in immediate termination of your account on our Service. <br /> You
          are responsible for safeguarding the password that you use to access
          the Service and for any activities or actions under your password,
          whether your password is with our Service or a third-party service.{" "}
          <br /> You agree not to disclose your password to any third party. You
          must notify us immediately upon becoming aware of any breach of
          security or unauthorized use of your account. <br /> You may not use
          as a username the name of another person or entity or that is not
          lawfully available for use, a name or trademark that is subject to any
          rights of another person or entity other than you without appropriate
          authorization, or a name that is otherwise offensive, vulgar or
          obscene. <br /> Intellectual Property <br /> The Service and its
          original content, features and functionality are and will remain the
          exclusive property of DevCircle Africa and its licensors. <br /> Links
          To Other Web Sites <br /> Our Service may contain links to third-party
          web sites or services that are not owned or controlled by DevCircle
          Africa. <br /> DevCircle Africa has no control over, and assumes no
          responsibility for, the content, privacy policies, or practices of any
          third party web sites or services. You further acknowledge and agree
          that DevCircle Africa shall not be responsible or liable, directly or
          indirectly, for any damage or loss caused or alleged to be caused by
          or in connection with use of or reliance on any such content, goods or
          services available on or through any such web sites or services.{" "}
          <br /> We strongly advise you to read the terms and conditions and
          privacy policies of any third-party web sites or services that you
          visit. <br /> Termination <br />
          We may terminate or suspend your account immediately, without prior
          notice or liability, for any reason whatsoever, including without
          limitation if you breach the Terms. <br /> Upon termination, your
          right to use the Service will immediately cease. If you wish to
          terminate your account, you may simply discontinue using the Service.{" "}
          <br /> All provisions of the Terms which by their nature should
          survive termination shall survive termination, including, without
          limitation, ownership provisions, warranty disclaimers, indemnity and
          limitations of liability. <br /> We may terminate or suspend your
          account immediately, without prior notice or liability, for any reason
          whatsoever, including without limitation if you breach the Terms.{" "}
          <br /> Upon termination, your right to use the Service will
          immediately cease. If you wish to terminate your account, you may
          simply discontinue using the Service. <br /> All provisions of the
          Terms which by their nature should survive termination shall survive
          termination, including, without limitation, ownership provisions,
          warranty disclaimers, indemnity and limitations of liability. <br />{" "}
          Governing Law <br /> These Terms shall be governed and construed in
          accordance with the laws of Nigeria without regard to its conflict of
          law provisions. <br /> Our failure to enforce any right or provision
          of these Terms will not be considered a waiver of those rights. If any
          provision of these Terms is held to be invalid or unenforceable by a
          court, the remaining provisions of these Terms will remain in effect.
          These Terms constitute the entire agreement between us regarding our
          Service, and supersede and replace any prior agreements we might have
          between us regarding the Service. <br /> Changes <br /> We reserve the
          right, at our sole discretion, to modify or replace these Terms at any
          time. If a revision is material we will try to provide at least 30
          days notice prior to any new terms taking effect. What constitutes a
          material change will be determined at our sole discretion. <br /> By
          continuing to access or use our Service after those revisions become
          effective, you agree to be bound by the revised terms. If you do not
          agree to the new terms, please stop using the Service. <br /> Contact
          Us <br /> If you have any questions about these Terms, please contact
          us. <br /> By email: support@devcircleafrica.com and you will be attended.{" "}
        </p>
      </p>
      <div>
        <h1 className="text-2xl font-medium text-[#00df9a]">Our Team </h1>
        <p className="text-white">
          We are a team of passionate developers, designers, and writers who are
          committed to creating the best possible experience for our users. We
          believe that technology should be accessible to everyone, and we
          strive to make our products as easy to use as possible. Our goal is to
          provide you with a platform where you can learn, share, and connect
          with others who share your interests. We hope you enjoy using our
          products as much as we enjoy building them! Happy Coding
        </p>
      </div>
    </div>
  );
}
